/* CONDIÇÃO 'OR' OU 'IN' */

USE BANK;

/* USANDO O 'OR' */

SELECT ACCOUNT_ID,
	   PRODUCT_CD,
	   CUST_ID,
	   AVAIL_BALANCE
FROM ACCOUNT
WHERE PRODUCT_CD = 'CHK'	
	  OR PRODUCT_CD = 'SAV'
	  OR PRODUCT_CD = 'CD'
	  OR PRODUCT_CD = 'MM';

/* USANDO O 'IN' */

SELECT ACCOUNT_ID,
	   PRODUCT_CD,
	   CUST_ID,
	   AVAIL_BALANCE
FROM ACCOUNT
WHERE PRODUCT_CD IN ('CHK', 'SAV', 'CD', 'MM');
