/* CORINGAS '_' (EXATAMENTE 1 CARACTER) OU '%' (QUALQUER NÚMERO DE CARACTER) */
/* PARA USAR OS CORINGAS UTILIZA A FUNCAO 'LIKE' */

USE bank;


SELECT LNAME
FROM employee
WHERE LNAME LIKE '_a%e%';


SELECT EMP_ID,
	   FNAME,
	   LNAME
FROM employee
WHERE LNAME LIKE 'F%' OR LNAME LIKE	'G%';

